In [2]:
# numpyの読み込み
import numpy as np

# 行列AとBを定義
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# 行列の積を計算
C = np.dot(A, B)

# 計算結果を表示
print("行列A:")
print(A)
print("行列B:")
print(B)
print("行列C（AとBの積）:")
print(C)

# 行列Cの要素の最大値を求める
max_value = np.max(C)

# 最大値を表示
print("行列Cの要素の最大値:", max_value)

行列A:
[[0 1]
 [2 3]
 [4 5]]
行列B:
[[0 1 2 3]
 [4 5 6 7]]
行列C（AとBの積）:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列Cの要素の最大値: 47
